apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: chatglm3-6b
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
  name: chatglm3-6b
  namespace: user1
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: vllm-runtime
      storage:
        key: aws-connection-minio
        path: models/chatglm3-6b
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: PreferNoSchedule
      key: gpu-workload-only
      operator: Exists
    nodeSelector:
      gpu-node-type: "2"
