apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: multilingual-e5-large
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
  name: multilingual-e5-large
  namespace: user1
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
      name: ""
      args:
      - --port
      - "3000"
      runtime: multilingual-e5-large-hf-tei
      storage:
        key: aws-connection-minio
        path: models/multilingual-e5-large
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - effect: PreferNoSchedule
      key: gpu-workload-only
      operator: Exists
    nodeSelector:
      gpu-node-type: "3"
